### ISSUE TITLE
Add grunt tasks in npm scripts

### ISSUE THREAD

**Issue by rpanneel** [lemaiwo/GitLab-CI-UI5-DemoApp#1]
Hi Wouter,

Doesn't it make sense to link your grunt tasks in npm scripts?

For example:
`
{
...,
"scripts": {
   "build": "grunt build",
   "fiori-test": "grunt fiori-test",
  ...
}
}
`

This way you would be able to make your .gitlab-ci.yml scripts a bit more readable in my opinion:

```yaml
code-validation: 
   stage: validation 
   script: 
     - npm run fiori-test
   dependencies:
    - init-ci
```
